"""Public classification contracts and DeepSeek adapter."""

from market_intelligence.classification.classifier import (
    ArticleClassifier,
    ClassificationConfigurationError,
    ClassificationError,
    ClassificationErrorCategory,
    build_classification_input,
    validate_article_source,
    validate_classification_rights,
)
from market_intelligence.classification.deepseek import (
    DEEPSEEK_MODEL,
    DeepSeekSettings,
    DeepSeekV4FlashClassifier,
    create_deepseek_classifier_from_environment,
)
from market_intelligence.classification.deterministic import (
    DEFAULT_DETERMINISTIC_RULES_PATH,
    DeterministicClassifier,
    DeterministicDisposition,
    DeterministicResult,
    DeterministicRules,
    MatchedEvidence,
    load_deterministic_rules,
    normalize_matching_text,
)
from market_intelligence.classification.hybrid import HybridArticleClassifier
from market_intelligence.classification.models import (
    CLASSIFIER_VERSION,
    DETERMINISTIC_RULES_VERSION,
    HYBRID_CLASSIFIER_VERSION,
    PROMPT_VERSION,
    TAXONOMY_VERSION,
    ClassificationInput,
    ClassificationMethod,
    ClassificationResult,
    ClassificationUsage,
    ClassifiedArticle,
    ProviderClassificationOutput,
    Topic,
)

__all__ = [
    "CLASSIFIER_VERSION",
    "DETERMINISTIC_RULES_VERSION",
    "HYBRID_CLASSIFIER_VERSION",
    "DEEPSEEK_MODEL",
    "PROMPT_VERSION",
    "TAXONOMY_VERSION",
    "ArticleClassifier",
    "ClassificationConfigurationError",
    "ClassificationError",
    "ClassificationErrorCategory",
    "ClassificationInput",
    "ClassificationMethod",
    "ClassificationResult",
    "ClassificationUsage",
    "ClassifiedArticle",
    "DeepSeekSettings",
    "DeepSeekV4FlashClassifier",
    "DeterministicClassifier",
    "DeterministicDisposition",
    "DeterministicResult",
    "DeterministicRules",
    "MatchedEvidence",
    "HybridArticleClassifier",
    "DEFAULT_DETERMINISTIC_RULES_PATH",
    "ProviderClassificationOutput",
    "Topic",
    "build_classification_input",
    "create_deepseek_classifier_from_environment",
    "load_deterministic_rules",
    "normalize_matching_text",
    "validate_article_source",
    "validate_classification_rights",
]
