"""Public secondary discovery admission boundary API."""

from market_intelligence.discovery.admission import (
    PublisherRouteConfigError,
    admit_candidate,
    build_source_index,
    evaluate_admission,
    normalize_path_for_matching,
    resolve_publisher_route,
    validate_publisher_routes,
)
from market_intelligence.discovery.benchmark import (
    MINIMUM_COMPLETED_DAYS,
    MINIMUM_ELIGIBLE_SAMPLE_SIZE,
    DirectPathPolicy,
    DiscoveryDelayPercentiles,
    SentinelObservation,
    capture_within_24h_rate,
    capture_within_60m_rate,
    discovery_delay_percentiles,
    duplicate_candidate_rate,
    evaluate_benchmark_tier,
    evaluate_direct_path_disposition,
    missed_after_24h,
    unknown_publisher_rate,
)
from market_intelligence.discovery.models import (
    AdmissionDecision,
    BenchmarkTier,
    DirectPathDisposition,
    DiscoveryCandidate,
    DiscoveryProvider,
    DiscoveryQuery,
    GdeltDiscoveryRole,
    IdentityMode,
    ObservationStatus,
    PublisherResolution,
    PublisherRoute,
    RouteResolutionStatus,
)
from market_intelligence.discovery.routes import load_publisher_routes

__all__ = [
    "MINIMUM_COMPLETED_DAYS",
    "MINIMUM_ELIGIBLE_SAMPLE_SIZE",
    "AdmissionDecision",
    "BenchmarkTier",
    "DirectPathDisposition",
    "DirectPathPolicy",
    "DiscoveryCandidate",
    "DiscoveryDelayPercentiles",
    "DiscoveryProvider",
    "DiscoveryQuery",
    "GdeltDiscoveryRole",
    "IdentityMode",
    "ObservationStatus",
    "PublisherResolution",
    "PublisherRoute",
    "PublisherRouteConfigError",
    "RouteResolutionStatus",
    "SentinelObservation",
    "admit_candidate",
    "build_source_index",
    "capture_within_24h_rate",
    "capture_within_60m_rate",
    "discovery_delay_percentiles",
    "duplicate_candidate_rate",
    "evaluate_admission",
    "evaluate_benchmark_tier",
    "evaluate_direct_path_disposition",
    "load_publisher_routes",
    "missed_after_24h",
    "normalize_path_for_matching",
    "resolve_publisher_route",
    "unknown_publisher_rate",
    "validate_publisher_routes",
]
